### ISSUE TITLE
how to actually use this app? 

### ISSUE THREAD

**Issue by wakandan** [luckman212/frontapp#1]
I run `./AppDelegate` but the app doesn't do anything.

**Comment by magnomad** [comment]
mad isn't it. I typed `swift AppDelegate.swift ` and got a bunch of errors.

`AppDelegate.swift:40:1: error: 'NSApplicationMain' attribute cannot be used in a module that contains top-level code
@NSApplicationMain
^
AppDelegate.swift:1:1: note: top-level code defined in this source file
//
^
AppDelegate.swift:1:1: note: pass '-parse-as-library' to compiler invocation if this is intentional
//
^
`

**Comment by magnomad** [comment]
you might have more luck with the python script here

https://apple.stackexchange.com/questions/123730/is-there-a-way-to-detect-what-program-is-stealing-focus-on-my-mac

**Comment by luckman212** [comment]
You don't run this from a Terminal. Download the release and double click the app like any other.

**Comment by magnomad** [comment]
Nope. That just opens a text file showing your source code.

**Comment by luckman212** [comment]
I'll double check later today but this sounds like somethings misconfigured with your LaunchServices database.

**Comment by luckman212** [comment]
I downloaded the latest release, unzipped, and ran it. Worked for me. @magnomad upload a screen recording of yourself doing the same please, maybe that will shed some light.
